# Variables: %player% %killer% %dmg% %totaldmg%
dmglisttitle: "&7--- &dDamage dealt (%totaldmg% total dmg) &7---"
dmglistentry: "&a%player% &7- &c%dmg% dmg &7- &c%crystals% crystals"

killermsg: "&d%killer% has killed the Ender Dragon!"
announcekiller: true

worldonlymsg: false
worldname: world_the_end

#Award variables are the same as for messages. 

#Award for the dragon killer.
enablekillerrewards: false
killrewards:
    - "give %killer% dragon_egg 1"
    
#Dmg awards have a chance relative to % dmg done to the dragon (eg 20 out of 100 dmg is a 20% chance).
enabledmgrewards: false
dmgrewards:
    - "give %player% elytra 1"
