name: Dragon-dmg
version: ${project.version}
description: Show damage done to the ender dragon after the kill
author: Hraponssi
main: net.hraponssi.dragondmg.main.Main
api-version: 1.13
commands:
  dragondmg:
    description: Manage dragon dmg
    usage: /<command> <subcommand>
    permission: dragondmg.dragondmg
permissions:
  dragondmg.dragondmg:
    description: Allows you to run /dragondmg
    default: op
